### ISSUE TITLE
OVH credentials leak

### ISSUE THREAD

**Issue by danielskowronski** [theclimber/ovhmail-password#2]
When soapConnect fails to connect script dumps function call with expanded variables to user - yes, it means that nicHande and plaintext password can be obtained.

**Comment by antenore** [comment]
Do you please have a solution/workaround for this issue? 

EDIT: Just noticed your pull request #3 that should fix this, right?

**Comment by theclimber** [comment]
Yes, it must be better now, I just merged the pull request

**Comment by antenore** [comment]
Cool! Thanks a lot!
